gsoc blog: purna
pymc-devs/pymc.io pull request #42
Opened 2022-06-24 20:24 UTC by reshamas

2022-06-24 20:28 UTC, reshamas commented
[@purna135](https://github.com/purna135), please review:
https://pymcio--42.org.readthedocs.build/welcome.html

2022-06-26 01:22 UTC, cluhmann requested changes
Picture seems much larger than needed.  @OriolAbril can weigh in about whether it's possible to resize using the markdown style image links or whether it requires an image directive.  Other than that, it looks good to me.

2022-06-27 21:19 UTC, OriolAbril commented on blog/blog_gsoc_2022.md
> +- GitHub: [@purna135](http://github.com/purna135)
```suggestion
**Project Name**

Increase Support for Batched Multivariate Distributions

::::{grid}
:::{grid-item} 
:columns: 12 6 6 4

![photo of Purna Chandra Mansingh](../_static/gsoc_2022/purna.jpg)
:::
:::{grid-item}
:columns: 12 6 6 8

**Bio**
>I am a final-year student at Hyderabad Central University pursuing a Master's in Computer Applications. I've been working in the fields of data science and machine learning for the past year. I enjoy working on complex problems and am a technical instructor. In my spare time, I enjoy contributing what I've learned to open-source projects.

**Connecting** 
- Twitter: [@purna_mansingh](https://twitter.com/purna_mansingh)
- LinkedIn: [purna135](https://www.linkedin.com/in/purna135/)
- GitHub: [@purna135](http://github.com/purna135)
:::
::::
```

2022-06-27 21:28 UTC, OriolAbril commented
How does this look?

The 4 numbers config indicates the width on different screen sizes. It uses a system of 12 columns total. Therefore, for small screens, both items are full width, the image comes before, then the text. For medium and largish screens, the width is divided half-half, for big screens, the text is twice as wide as the image.

We can change the order and or move content in and out of the grid elements as needed.

---

big screen:
![image](https://user-images.githubusercontent.com/23738400/176038164-594c9e7c-3b79-4060-860e-658e8912f14c.png)

medium screen (ipad simulated on firefox dev tools)
![image](https://user-images.githubusercontent.com/23738400/176038234-110695a5-554f-425a-9266-34a12a87b3fe.png)

small screen (iphone se simulated of firefox dev tools)
![image](https://user-images.githubusercontent.com/23738400/176038339-3c43090c-a48b-4ec7-bd56-ca5340e2a9cc.png)

2022-06-27 23:06 UTC, reshamas commented on blog/blog_gsoc_2022.md
> +    GSoC is a place where I can not only apply my existing skills but also learn new ones. And the learning does not stop with technical knowledge. GSoC introduces me to a new paradigm for collaborat
Adding a single line break for question 1

2022-06-27 23:09 UTC, reshamas commented on blog/blog_gsoc_2022.md
> +
```suggestion
**Project Name**

Increase Support for Batched Multivariate Distributions

**Mentors**
- [Sayam Kumar](https://github.com/Sayam753)
- [Ricardo Vieira](https://github.com/ricardoV94)
```

2022-06-27 23:10 UTC, reshamas commented on blog/blog_gsoc_2022.md
> +
@OriolAbril What do you think of adding the Mentors names? 
I think it would be nice to add their name(s).

2022-06-28 00:27 UTC, cluhmann approved these changes
Looks great to me.

2022-06-28 11:12 UTC, reshamas commented
This looks great!  Thanks [@purna135](https://github.com/purna135), @OriolAbril , @cluhmann

2022-06-28 11:12 UTC, merged